package poza.soulmirror.firebase;

import androidx.annotation.NonNull;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;
import java.util.List;

import poza.soulmirror.FirebaseCallback;
import poza.soulmirror.beans.AppelBean;

public class DonneesFirebase {
    public static void ajoutDonnees(FirebaseCallback<List<AppelBean>> callback){
        // Obtenir la référence à la base de données
        DatabaseReference databaseRef = FirebaseDatabase.getInstance().getReference().child("centres_appels");
        List<AppelBean> appel = new ArrayList<>();
        // Créer et ajouter les donénes à la liste
        appel.add(new AppelBean(1,"Aide aux victimes","116 006","De 9h à 19h, 7j/7. Vous ou un proche êtes victimes de violences physiques, sexuelles ou psychologiques,au sein de la famille ou en dehors, d'un accident de la route, d'un vol ou d'une escroquerie, ou de n'importe quel autre fait qui vous a porté préjudice.", "https://www.france-victimes.fr/index.php"));
        appel.add(new AppelBean(2,"Alcool Info Service","09.80.98.09.30","De 8h à 2h, 7j/7. Appel anonyme et non surtaxé - Coûr d'une communication locale depuis un poste fixe, inclus dans les forfaits des boxs ou mobiles. Pour les personnes directement ou indirectement concerné. A votre écoute des professionnels formés aux problèmes d'usage et de dépendance à l'alcool, une écoute sans jugement et confidentielle, des informations précises, une aide personnalisée, des orientations adaptées à votre situation.", "https://www.alcool-info-service.fr/"));
        appel.add(new AppelBean(3,"Alcooliques Anonymes","09.69.39.40.20","24h/24 - Appel non surtaxé.  La personne qui vous répondra est un alcoolique abstinent, membre des AA, qui a connu lui-même votre situation, il saura vous écouter sans vous juger. Il pourra vous proposer de rencontrer des AA près de chez vous, qui vous accompagneront dans vos premiers pas.", "https://alcooliques-anonymes.fr/"));
        appel.add(new AppelBean(4,"Allo Ecoute Parents (pour les parents d'adolescents)","06.01.18.40.36","Du lundi au vendredi, de 13h à 15h.", "https://www.alloecouteparents.org/"));
        appel.add(new AppelBean(5,"Allô Enfance en Danger","119","7j/7, 24h/24. - Gratuit depuis tous les téléphones fixes et mobiles. - Numéro national joignable de toute la France et des Départements d'Outre-mer (Guadeloupe, Guyane, Martinique, Réunion, Mayotte). Ce numéro n'apparaît sur aucun relevé téléphonique. Respect de la confidentialité des appels. 45 écoutants, professionnels de l'enfance, se relaient pour répondre aux appels.", "https://www.allo119.gouv.fr/"));
        appel.add(new AppelBean(6,"Allo Parents Bébé (à destination des jeunes parents ayant besoin de conseil)","08.00.00.34.56","Du lundi au vendredi, de 10h à 13h et de 14h à 18h. - Gratuit. Ligne d'écoute pour les personnes qui attendent un enfant, ou parents d'un enfant de moins de 3 ans, qui se posent des questions sur la relation avec leur bébé ou sur un comportement, qui sont inquiets et se sentent débordé, démunis face à de nouvelles situations, qui ne savent pas à qui parler ni comment en parler.", "https://enfance-et-partage.org/la-prevention/allo-parents-bebe/"));
        appel.add(new AppelBean(7,"Anorexie Boulimie, Info Ecoute","09.69.32.59.00","Les lundis, mardis, jeudis et vendredis, de 16h à 18h. Numéro d'écoute à destination des patients, familles et proches concernés par la boulimie ou l'anorexie.", "https://www.ffab.fr/"));
        appel.add(new AppelBean(8,"Argos (troubles bipolaires)","01.46.28.01.03","Du lundi au vendredi de 10h à 13h. Ses activités essentielles consistent dans des groupes de paroles pour les patients et leur proches ainsi que des conférences faite par des psychiatres spécialisés sur les troubles bipolaires, elle dispose également d'une ligne d'écoute.", "https://argos2001.net/"));
        appel.add(new AppelBean(9,"Association Empreintes","01.42.38.08.08","Les lundis et vendredi, de 9h30 à 17h30, les mardis et mercredis de 9h30 à 20h30, les jeudis de 9h30 à 12h et de 18h à 20h30. Sa spécificité est d'accompagner toute personne en deuil quel que soit l'âg de l'endeuillé et du défunt, quel que soit le lien de l'endeuillé avec le défunt, quelles que soient les causes et les circonstances du décès.", "https://www.empreintes-asso.com/"));
        appel.add(new AppelBean(10,"Association Française des Sclérosés en Plaque (AFSEP)","08.10.80.32.95","Propose une ligne d'écoute psychologique pour avoir un soutien psychologique adapté, en particulier après l'annonce du diagnostic ou en période de difficultés.", "https://afsep.fr/au-quotidien/ligne-decoute-psychologique/"));
        appel.add(new AppelBean(11,"Autisme Info Service","08.00.71.40.40","Du lundi au vendredi de 9h à 13h et le mardi de 9h à 13h et de 18h à 20h. Premier dispositif national d'écoute et d'information permettant d'aider et d'orienter les personnes avec autisme et leur entourage.", "https://www.autismeinfoservice.fr/"));
        appel.add(new AppelBean(12,"Avec Nos Proches","01.84.72.94.72","De 8h à 22h, 7j/7 - Prix d'un appel local et anonyme. Pour les personnes qui accompagne un proche fragilisé par la maladie, le handicap ou l'âge, vous avez des questions, es doutes, besoin de soutien, de prendre du recul, une première réponse se trouve peut-être au bout du fil.", "https://www.avecnosproches.com/"));
        appel.add(new AppelBean(13,"Croix-Rouge Ecoute","08.00.85.88.58","Du lundi au samedi de 9h à 18h et le dimanche de 12h à 18h, ou 09 70 28 30 00, du lundi au samedi de 9h à 19h – Appel et service gratuits Service de soutien psychologique et de livraison solidaire.", "https://www.croix-rouge.fr/soutien-psychosocial-par-telephone/"));
        appel.add(new AppelBean(14,"Drogues Info Services","08.00.23.13.13","De 8h à 2h, 7j/7. Appel anonyme et gratuit. Pour les personnes concerné directement ou indirectement par une consommation de drogues. A votre écoute, des professionnels formés aux problèmes d'usage et de dépendance aux drogues, une écoute sans jugement et confidentielle, des informations précises, une aide personnalisée, des orientations adaptées à votre situation.", "https://www.drogues-info-service.fr/"));
        appel.add(new AppelBean(15,"Ecoute défense","08.08.80.03.21","Tous les jours, 24h/24 - Appel et service gratuits. Ecoute, soutien, information, orientation des militaires, ex-militaires, familles de militaires et civils de la défense à des situations de stress et traumatismes psychiques en service.", "https://www.defense.gouv.fr/sante/dossiers-complementaires/classeur-stress-post-traumatique/contacts-ecoute-defense/"));
        appel.add(new AppelBean(16,"Ecoute-famille","01 42 63 03 03","Du lundi au vendredi de 9h à 13h et de 14h à 18h (17h le vendredi) - Coût d'une communication locale. Information, orientation et soutien psycholgique de personnes confrontées aux troubles psychiques d'un proche.", "https://www.unafam.org/nos-actions/accueil-ecoute-et-information/"));
        appel.add(new AppelBean(17,"Enfance et Partage","08.00.05.12.34","Du lundi au vendredi, de 10h à 18h. L'association permet de recueillir des informations préoccupantes sur des mineurs maltraités ou en danger de maltraitance. Il donne également accès à un accompagnement juridique et psychologique.", "https://enfance-et-partage.org/"));
        appel.add(new AppelBean(18,"Enfine (Autour des troubles du comportement alimentaire)","01.40.72.64.44","Mardi et jeudi, de 20h à 22h. Ligne d'écoute qui s'adresse à toutes les personnes qui sont touchées par les troubles du comportement alimentaire (TCA), directement ou indirectement. Que vous souffriez vous-même d'un TCA ou que vous soyez un parent, un conjoint, un proche, les écoutants sont là pour vous accueillir, vous écouter et parler avec vous.", "https://www.enfine.com/"));
        appel.add(new AppelBean(19,"Fédérations 3977 (maltraitances envers les personnes âgés et les personnes handicapés)","3977","Du lundi au vendredi, de 9h à 19h et le samedi et dimanche de 9h à 13h et de 14h à 19h. Numéro national dédié à lutter contre les maltraitances envers les personnes âgés et les majeurs en situation de handicap.", "https://3977.org/"));
        appel.add(new AppelBean(20,"France Acouphène","08 20 22 22 13","Du lundi au vendredi, de 9h à 20h. Totalement indépendante, l'association est animée par des bénévoles souffrant eux-mêmes d'acouphènes, d'hyperacousie, de la maladie de Menière, de neurinome de l'acoustique.", "https://www.france-acouphenes.fr/"));
        appel.add(new AppelBean(21,"France Depression","07 84 96 88 28","Du lundi au samedi, de 9h à 20h et le dimanche de 14h à 20h. L'association a pour mission de prévenir, d'informer, de soutenir les personnes souffrant de dépression ou de troubles bipolaires, de lutter contre la stigmatisation et de promouvoir leur dignité et le respect de leurs droits au niveau local, national et européen.", "https://francedepression.fr/"));
        appel.add(new AppelBean(22,"France Parkinson","01 43 43 43 15","Du lundi au vendredi, de 9h30 à 12h30.", "https://www.franceparkinson.fr/"));
        appel.add(new AppelBean(23,"Hépatites Info Service","08 00 84 58 00","De 8h à 21h 7j/7 - Anonyme, confidentiel et gratuit à partir d'un poste fixe et d'un mobile. Que vous soyez malade ou proche d'une personne touchée, que vous envisagiez de faire un test de dépistage ou non, que vous soyez en attente de résultats. Chaque appel est accueilli avec respect et sans jugement. La confidentialité permet à chacun de s'exprimer librement.", "https://www.hepatites-info-service.org/"));
        appel.add(new AppelBean(24,"Joueurs Info Service","09 74 75 13 13","De 8h à 2h, 7j/7. Appel anonyme et gratuit. Pour les personnes concerné directement ou indirectement par un problème de jeu excessif. A votre écoute, des professionnels formés aux difficultés rencontrées avec la pratique de jeu excessif, une écoute sans jugement et confidentielle, des informations précises, une aide personnalisée, des orientations adaptées à votre situation.", "https://www.joueurs-info-service.fr/"));
        appel.add(new AppelBean(25,"Ligne d'écoute du Refuge","06 31 59 69 50","Téléphone et SMS, tous les jours, 24h/24 - Coût d'une communication mobile. Accueil, soutien, information, orientation des jeunes LGBT victimes d'homophobie ou de transphobie et en situation de rupture familiale.", "https://www.le-refuge.org/"));
        appel.add(new AppelBean(26,"Ligue Contre le Cancer","08 00 94 09 39","Du lundi au vendredi de 9h à 19h. Des psychologues cliniciens vous proposent une écoute ponctuelle, attentive et active.", "https://www.ligue-cancer.net/"));
        appel.add(new AppelBean(27,"Numéro national de Prévention du Suicide","3114","Accessible tous les jours, 24h/24 – Appel confidentiel et gratuit Ecoute, évaluation, orientation et intervention auprès des personnes ayant des idées suicidaires, inquiètes pour un proche ou confrontées au suicide. Ligne également ouverte aux professionnels qui souhaitent des informations ou un appui pour l’accompagnement d’une personne repérée comme à risque suicidaire.", "https://3114.fr/"));
        appel.add(new AppelBean(28,"Phare Enfants Parents","01 43 46 00 62","Du lundi au vendredi de 10h à 17h Accueil et écoute des parents confrontés au mal-être et au suicide des jeunes.", "https://www.phare.org/"));
        appel.add(new AppelBean(29,"Schizo ? ... Oui ! (troubles schizophréniques)","01 45 89 49 44","Du lundi au vendredi, de 9h à 13h - Service gratuit d'orientation juridique sur le droit des malades tenu par un-e conseiller-ère. Lundi, mercredi et vendredi, de 13h30 à 18h30 - Service gratuit d'écoute sur la schizophrénie tenu par une psychologue clinicienne.", "https://www.schizo-oui.com/"));
        appel.add(new AppelBean(30,"Sida Info Service","08 00 84 08 00","De 8h à 23h, 7j/7 (jours fériés compris). Appel gratuit (depuis un poste fixe et portable) et non décompté des forfaits depuis la France. Que vous soyez séronégatif-ve, séropositif-ve, malade ou proche d'une personne touchée, que vous n'ayez pas fait le test de dépistage ou que vous soyez en attente de résultats. Chaque appel est accueilli avec respect, sans jugement. La confidentialité permet à chacun-e de s'exprimer librement.", "https://www.sida-info-service.org/"));
        appel.add(new AppelBean(31,"Sida Info Service depuis l'étranger(même depuis un pays de l'UE","+33 1 41 83 42 77","Coût de l'appel à la charge de l'appelant afin d'éviter toute surtaxe.", "https://www.sida-info-service.org/"));
        appel.add(new AppelBean(32,"Solitud'écoute","08 00 47 47 88","Tous les jours de 15h à 20h. Appel et service gratuits Accueil et écoute des personnes de + de 50 ans.", "https://www.petitsfreresdespauvres.fr/nos-actions/apporter-une-presence/ecoute-anonyme/"));
        appel.add(new AppelBean(33,"SOS Amitié","09 72 39 40 50","Tous les jours, 24h/24 – Appel et service gratuits Accueil et écoute des personnes en détresse et de leur entourage.", "https://www.sos-amitie.com/"));
        appel.add(new AppelBean(34,"SOS Crise","08 00 19 00 00","Tous les jours, de 9h à 19h – Appel et service gratuits Ecoute, soutien, information et orientation des personnes en détresse.", "https://www.lestransmetteurs.org/soscrise/"));
        appel.add(new AppelBean(35,"SOS Joueurs","09 69 39 55 12","Association a but non lucratif dont les services d'aide sont gratuits. Avocat, assistant social, psycologue, etc. Pour l'addiction aux jeux d'argent comme pour l'addiction aux jeux vidéo, les intervenants sont tous des professionnels spécialisés.", "https://sosjoueurs.org/"));
        appel.add(new AppelBean(36,"SOS Suicide Phénix","01 40 44 46 45","Tous les jours, de 13h à 23h - Coût d'une communication locale. Accueil et écoute des personnes en souffrance psychologique ou confrontées au suicide, et de leur entourage.", "https://sos-suicide-phenix.org/"));
        appel.add(new AppelBean(37,"Suicide Ecoute","01 45 39 40 00","Tous les jours, 24h/24 – Coût d’une communication locale Accueil et écoute des personnes en grande souffrance psychologique ou confrontées au suicide, et de leur entourage.", "https://www.suicide-ecoute.fr/"));
        appel.add(new AppelBean(38,"Tabac Info Service","3989","Du lundi au samedi de 8h à 20h. Un conseiller répondra à vos premières questions. Si vous le souhaitez, il vous mettra en relation avec un tabacologue. Accompagnement entièrement gratuit avec un suivi personnalisé. Ce sera toujours le même tabacologue qui vous accompagnera : vous fixerez avec lui des rendez-vous téléphoniques réguliers. C'est lui qui vous rappellera au moment que vous aurez choisi.", "https://www.tabac-info-service.fr/"));
        appel.add(new AppelBean(39,"Violences Femmes Info","3919","7j/7, 24h/24. - Gratuit depuis un poste fixe ou mobile en métropôle, comme dans les départements d'Outre-Mer. Les appels peuvent concerner tous les types de violences sexistes : (violences conjugales, violences sexuelles, mariages forcés, mutilations sexuelles féminines, violences au travail), de leur entourages ou des professionnels concernés. Ce numéro national garantit une écoute, une information et, en fonction des demandes, une orientation adaptée vers les dispositifs locaux d'accompagnement et de prise en charge. En plus du français il est possible d'obtenir des informations, une orientation ou une écoute téléphonique dans 12 langues différentes : anglais, arabes, créole, dari, espagnol, hébreu, kabyle, mandarin, persan, polonais, portugais et turc, cependant, les écoutantes ou chargées de pré-accueil pouvant assurer ce service ne sont pas présentes 24h/24, aussi l'appelant-e pourra être invité-e à rappeler aux horaires indiqués par l'équipe du 3919.", "https://solidaritefemmes.org/"));
        appel.add(new AppelBean(40,"Viols Femmes Informations","08 00 05 95 95","Du lundi au vendredi, de 10h à 19h. Gratuit y compris depuis les portables, anonyme et confidentielle. Pour les personnes ayant été victimes de violences sexuelles, qui se posent des questions sur ce qu'elles ont vécu, qui veulent aider une personne de leur entourage, qui recherchent des conseils en tant que professionnels.", "https://cfcv.asso.fr/"));

        // Ajout des données à Firebase
        for (AppelBean appelBean : appel){
            databaseRef.push().setValue(appelBean);
        }
    }
}
